//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string MaHD { get; set; }
        public string MaGame { get; set; }
        public string MaKH { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
